export const CONTEXT: string = 'DASHBOARD';

/**
 * COUNTERAction  Interface
 */
interface IDashboardActions {
    INIT: string;
    INITIALIZED: string;
    INIT_FAILED: string;
    GET_DASHBOARD_LIST: string;
    GET_DASHBOARD_SUCCESS: string;
    ADD_DASHBOARD: string;
    ADD_DASHBOARD_SUCCESS: string;
    ON_FAILED: string;
}

/**
 * COUNTER Actions List
 */
export const DASHBOARD_ACTIONS: IDashboardActions = {
    INIT: `${CONTEXT}_INIT`,
    INITIALIZED: `${CONTEXT}_INITIALIZED`,
    INIT_FAILED: `${CONTEXT}_INIT_FAILED`,
    GET_DASHBOARD_LIST: `${CONTEXT}_GET_DASHBOARD_LIST`,
    GET_DASHBOARD_SUCCESS: `${CONTEXT}_GET_DASHBOARD_SUCCESS`,
    ADD_DASHBOARD: `${CONTEXT}_ADD_DASHBOARD`,
    ADD_DASHBOARD_SUCCESS: `${CONTEXT}_ADD_DASHBOARD_SUCCESS`,
    ON_FAILED: `${CONTEXT}_ON_FAILED`,
};